name: aligned_dialog
description: Show a locally/globally aligned dialog with custom transtion animation.
version: 0.0.1
homepage: https://github.com/KevinVan720/aligned_dialog.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

